name: Trigger Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Send trigger to test repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: sJoven/weather-tracker-test-playwright
          event-type: run-playwright-tests
